Updated Start From Scratch
testomatio/docs pull request #92
Opened 2024-07-10 18:15 UTC by maxkryvoshyya

2024-07-16 19:36 UTC, poliarush commented
fix https://github.com/testomatio/testomatio/issues/4383

2024-07-17 19:09 UTC, DavertMik requested changes

2024-07-17 19:09 UTC, DavertMik commented on src/content/docs/getting-started/start-from-scratch.md
> +2. The **Fill demo data** checkbox is optional. This option fills the project with ready-made test data so that new users can try testomat.io quickly and easily. You can simply skip it.
```suggestion
2. The **Fill demo data** checkbox is optional. This option fills the project with ready-made test data so that new users can try Testomat.io quickly and easily. You can simply skip it. 
```

2024-07-17 19:09 UTC, DavertMik commented on src/content/docs/getting-started/start-from-scratch.md
> +We have implemented **Bulk edit**, which enables you to create as many test suites as you need:
Let's not use `We` and stay more formal here

As it's not clear who are "we":

* reader + author
* developers 

Also, I think Bulk Edit is an advanced topis and should be removed at all from Getting Started

2024-07-17 19:09 UTC, DavertMik commented on src/content/docs/getting-started/start-from-scratch.md
> +That's great! Now you can share the report with your stakeholders. It is just a tip of the iceberg, keep reading the documentation to discover [testomat.io](https://app.testomat.io)!
```suggestion
That's great! Now you can share the report with your stakeholders. It is just a tip of the iceberg, keep reading the documentation to discover [Testomat.io](https://app.testomat.io)!
```

2024-07-18 08:13 UTC, merged